name: authorization-service
namespace: 3scale-authorization-service
runtime: quarkus
image: quay.io/asoliman/authorization-service:latest
imageDigest: ""
trigger: http
builder: quay.io/boson/faas-quarkus-jvm-builder
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
env: {}
annotations: {}
